#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-digest
Version  : 0.6.12
Release  : 41
URL      : http://cran.r-project.org/src/contrib/digest_0.6.12.tar.gz
Source0  : http://cran.r-project.org/src/contrib/digest_0.6.12.tar.gz
Summary  : Create Compact Hash Digests of R Objects
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-digest-lib
BuildRequires : R-knitr
BuildRequires : R-markdown
BuildRequires : clr-R-helpers

%description
of hash digests of arbitrary R objects (using the 'md5', 'sha-1', 'sha-256', 
 'crc32', 'xxhash' and 'murmurhash' algorithms) permitting easy comparison of R
 language objects, as well as a function 'hmac()' to create hash-based
 message authentication code. Please note that this package is not meant to
 be deployed for cryptographic purposes for which more comprehensive (and
 widely tested) libraries such as 'OpenSSL' should be used.

%package lib
Summary: lib components for the R-digest package.
Group: Libraries

%description lib
lib components for the R-digest package.


%prep
%setup -q -c -n digest

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1502403099

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1502403099
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library digest
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library digest
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library digest
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library digest
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/digest/DESCRIPTION
/usr/lib64/R/library/digest/GPL-2
/usr/lib64/R/library/digest/INDEX
/usr/lib64/R/library/digest/Meta/Rd.rds
/usr/lib64/R/library/digest/Meta/features.rds
/usr/lib64/R/library/digest/Meta/hsearch.rds
/usr/lib64/R/library/digest/Meta/links.rds
/usr/lib64/R/library/digest/Meta/nsInfo.rds
/usr/lib64/R/library/digest/Meta/package.rds
/usr/lib64/R/library/digest/Meta/vignette.rds
/usr/lib64/R/library/digest/NAMESPACE
/usr/lib64/R/library/digest/R/digest
/usr/lib64/R/library/digest/R/digest.rdb
/usr/lib64/R/library/digest/R/digest.rdx
/usr/lib64/R/library/digest/doc/index.html
/usr/lib64/R/library/digest/doc/sha1.R
/usr/lib64/R/library/digest/doc/sha1.Rmd
/usr/lib64/R/library/digest/doc/sha1.html
/usr/lib64/R/library/digest/help/AnIndex
/usr/lib64/R/library/digest/help/aliases.rds
/usr/lib64/R/library/digest/help/digest.rdb
/usr/lib64/R/library/digest/help/digest.rdx
/usr/lib64/R/library/digest/help/paths.rds
/usr/lib64/R/library/digest/html/00Index.html
/usr/lib64/R/library/digest/html/R.css
/usr/lib64/R/library/digest/include/pmurhashAPI.h
/usr/lib64/R/library/digest/libs/symbols.rds

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/digest/libs/digest.so
/usr/lib64/R/library/digest/libs/digest.so.avx2
/usr/lib64/R/library/digest/libs/digest.so.avx512
